a = input('Digite algo: ')
print('O que foi digitado é do tipo primitivo ', type(a))
print('Se ele tem todas as letras maiúsculas', a.isupper())
print('Se ele tem letra ou número ', a.isalnum())
print('Se ele tem apenas letras ', a.isalpha())
print('', a.isascii())
print(a.isdigit())
print('Se ele tem números decimais ', a.isdecimal())
print(a.isidentifier())
print('Se ele tem letras minúsculas ', a.islower())
print('Se ele é um número ', a.isnumeric())
print(a.isprintable())
print('Se ele só tem espaços ', a.isspace())
print('Se está capitalizado ', a.istitle())
